# Generated by Django 6.0.5 on 2026-05-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('unit_name', models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('fl oz', 'Fluid Ounce'), ('c', 'Cup'), ('pt', 'Pint'), ('gal', 'Gallon'), ('ml', 'Milliliter'), ('l', 'Liter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('mg', 'Milligram'), ('cn', 'Can'), ('pkg', 'Package')], max_length=5)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Menu_Items',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
