# Generated by Django 6.0.5 on 2026-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracker', '0002_ingredient_menuitem_purchase_reciperequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_name',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('fl oz', 'Fluid Ounce'), ('c', 'Cup'), ('pt', 'Pint'), ('gal', 'Gallon'), ('ml', 'Milliliter'), ('l', 'Liter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('mg', 'Milligram'), ('cn', 'Can'), ('pkg', 'Package'), ('qty', 'Quantity')], max_length=5),
        ),
    ]
